### ISSUE TITLE
Specify font size for table

### ISSUE THREAD

**Issue by TheChymera** [TheChymera/matrix2latex#11]
Is there any argument for `matrix2latex()` that lets me specify a font size? I have tried defining one outside of the imported table in my document, but that does not seem to work. Any ideas if one of the args might already let me do this?

@obtitus

**Comment by obtitus** [comment]
No, not directly. There are a couple of options:
(1) Globally: \documentclass[15pt, a4paper]{article} 
(2) locally: \begin{big}\end{big} can be inserted in the environment, if you are outputting a table:
matrix2latex(m, filename, “big”, “table”, “center”, “tabular”)
or
matrix2latex(m, filename, environments=[“big”, “table”, “center”, “tabular”])

**Comment by TheChymera** [comment]
thanks!

**Comment by TheChymera** [comment]
Ok, small correction: the fontsize has to be specified *after* `table` in the environments list:

`environments=["table", "tiny", "center", "tabular"]`  works, while `environments=["tiny", "table", "center", "tabular"]` fails to set the size.
