### ISSUE TITLE
Dependencies are not satisfied

### ISSUE THREAD

**Issue by nicoguaro** [TheChymera/matrix2latex#12]
I downloaded matrix2latex, and installed it. I supposed that it would work, since it does not mention any dependencies. But it does not, it requires niceFloat. This [package](https://labix.org/python-nicefloat) seems to be the one, but it has a different name. Thus, I can't run the example provided in the README.

**Comment by TheChymera** [comment]
The example works for me, and I do not have nicefloat:

```
In [2]: from matrix2latex import matrix2latex

In [3]: m = [[1, 1], [2, 4], [3, 9]] # python nested list

In [4]: t = matrix2latex(m)

In [5]: print t
\begin{table}[htp]
	\begin{center}
		\begin{tabular}{cc}
		\toprule
			$1$ & $1$\\
			$2$ & $4$\\
			$3$ & $9$\\
		\bottomrule
		\end{tabular}
	\end{center}
\end{table}

In [6]: import nicefloat
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-2d34548ed64d> in <module>()
----> 1 import nicefloat

ImportError: No module named nicefloat

In [7]: import niceFloat
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-db92c1ac80ab> in <module>()
----> 1 import niceFloat

ImportError: No module named niceFloat
```

I am farily certain that matrix2latex has no deps in addition to vanilla python. @obtitus should be able to confirm this.

**Comment by obtitus** [comment]
Vops, sorry about that. Should be fixed in the latest (just remove the from niceFloat import nice line).

Seems my testing is not isolated, as I probably have a nicefloat lying around.  Matrix2latex used to be shipped with nicefloat, but at some point I stopped using it, removed the nicefloat file and forgot to remove the import.

**Comment by obtitus** [comment]
@TheChymera The other imports are from files shipped with matrix2latex, so no external dependencies. They should not be removed, as I believe they are all in use. The user simply needs to treat matrix2latex as a folder (python package).
