### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by obtitus** [TheChymera/matrix2latex#14]
@TheChymera  Since this is under your account, can you look at the travis integration? Seems I can't. They are migrating to https://www.travis-ci.com/account/repositories and seems some of the python versions are no longer supported. I tried to check in a new travis.yml file, but not sure if helped any.

**Comment by TheChymera** [comment]
@obtitus 
> I tried to check in a new travis.yml file, but not sure if helped any.

Where have you checked it in? I can't see any new PR, but I you have push access in any case. If you have a draft, maybe just push it and then we can see how travis deals with it.

**Comment by obtitus** [comment]
Nevermind, I had named the file travis.yml and not .travis.yml. Fixed now. I have push access, so no pull request :) Build now passing.
