### ISSUE TITLE
Provide versioned downloads

### ISSUE THREAD

**Issue by TheChymera** [TheChymera/matrix2latex#9]
Hi, I am packagig this package for Gentoo ^^

In addition to the `-9999` (live)  version, I would also like to provide some versioned versions. I already have the version with the source at https://matrix2latex.googlecode.com/files/matrix2latexPython2011-12-15.tar.gz listed under 0.1 - but based on the date I guess that is already ancient? 

@obtitus do you have some links to newer static versions (and perhaps a versioning scheme, which would allow me to circumvent date versioning)?

**Comment by obtitus** [comment]
Hmm, I have a utility script for packaging the project into .tar.gz files which is not commited (It was used for uploading to code.google). What versioning scheme would you like to use? We can call this release 1.0.0 if you want?

I also found another diff which was not commited, cleaning up...

**Comment by TheChymera** [comment]
Ok, let's call this `1.0.0` and let's also have a previous release (like, not long before we moved to github) called `0.9.9` ok?

**Comment by TheChymera** [comment]
As for the general versioning scheme I would propose:

* We make a new version whenever any of us feels it is in order, and bump the last number by 1.
* We bump the second number if we make any really big changes (e.g. adding a new family of modules, or updating the setup system)
* We bump the first number if we ever end up rewriting most of it, or if the second number just gets ridiculously high.

**Comment by obtitus** [comment]
Sounds like a plan. Version 1 should now be available here:
https://github.com/TheChymera/matrix2latex/blob/master/archive/matrix2latexPython-1.0.0.tar.gz?raw=true

Feel free to modify the archiver.py script if you want to generate a 0.9.9 (replace the "HEAD" string). 

I hope I have not left out any relevant files from these archives, let me know.
